### ISSUE TITLE
move fails when destination exists

### ISSUE THREAD

**Issue by nikolay-borzov** [xianweics/filemanager-plugin#1]
Webpack: `4.44.1`

Assume folders structure
```
dist/
build/
```

plugin instance:
```
new FileManagerPlugin({
  events: {
    end: {
      move: {
        items: [
          // Move entire `svg` directory
          { source: './build/svg', destination: './dist/svg' }
        ]
      }
    }
  }
})
```

After the first run:
```
dist/
  svg/{svg files}
build/
```

After the second run webpack build fails. I didn't manage to get error details.

**Comment by xianweics** [comment]
@nikolay-borzov Do you del it before rebuild?

**Comment by nikolay-borzov** [comment]
Yes. If a file exists it should be replaced with the updated version (like File Explorer in Windows does). 

I use this a workaround:
```
del: {
  // Prevent crash when files exist
  items: ['./build/svg']
},
move: {
  items: [
    { source: './build/svg', destination: './dist/svg' }
  ]
}
```

**Comment by xianweics** [comment]
@nikolay-borzov Good. I will enhance the feature that the file will not be replaced or updated unless the file is changed, and speed up rebuilding.

**Comment by xianweics** [comment]
Fix it. version >= 2.5.0
