### ISSUE TITLE
Copy doesn't seem to respect subfolders

### ISSUE THREAD

**Issue by dombarnes** [xianweics/filemanager-plugin#13]
Config
```
copy: {
            items: [
              {
                source: path.resolve(__dirname, "wwwroot/packs/**/*.js"),
                destination: path.resolve(__dirname, "wwwroot/js"),
              }
          ]
        }
```
Files inside `wwwroot/packs/subfolder/fileA.js` do not end up inside `wwwroot/js/subfolder/fileA.js`

Version: 2.7.2

**Comment by xianweics** [comment]
@dombarnes Thanks your feedback. I have already enhanced that copy feature by using `isFlat` to control folder structure as below. Please update to version `2.8.1` to try it. For more detail, please see `README.md`. 

```javascript
copy: {
  items: [
    {
      source: path.resolve(__dirname, "wwwroot/packs/**/*.js"),
      destination: path.resolve(__dirname, "wwwroot/js"),
      isFlat: false
    }
  ]
}
```
