### ISSUE TITLE
Ability to copy file with rename it

### ISSUE THREAD

**Issue by SPuV** [xianweics/filemanager-plugin#16]
Hi! 
I'd like to copy a file and rename it in one operation. 
But I get a folder named as the name of destination file with source file inside.
The code in document likes that:

```
copy: [
     { source: "./subfolder/oldName.css", destination: "./newName.css" }
]
```
Please add possibility to copy file with rename

**Comment by xianweics** [comment]
Thanks for your comment. The feature I have done.
You need to provide with the `name` parameter to rename. This is an example: 
```javascript
copy: [
     { source: "./subfolder/oldName.css", destination: "./", name: "newName.css" }
]
```
For the more detail, please check [ReadMe](https://github.com/xianweics/filemanager-plugin#copy-example).
Hopefully, It would help you.
