### ISSUE TITLE
vite不支持filemanager-plugin

### ISSUE THREAD

**Issue by sundaotong** [xianweics/filemanager-plugin#17]
Dynamic require of "file:///E:/provincialTrunk/gsgx-ha-front-pc/node_modules/filemanager-plugin/lib/index.js" is not supported

**Comment by sundaotong** [comment]
Dynamic require of "file:///E:/provincialTrunk/gsgx-ha-front-pc/node_modules/filemanager-plugin/lib/index.js" is not supported

**Comment by xianweics** [comment]
It cannot import dynamically from that `.../node_modules/filemanager-plugin/lib/index.js`.
Please read [README.md](https://github.com/xianweics/filemanager-plugin#readme) file.
