### ISSUE TITLE
插件执行的时机

### ISSUE THREAD

**Issue by M69W** [xianweics/filemanager-plugin#20]
因项目需要，同时使用 [vite-plugin-compression](https://github.com/vbenjs/vite-plugin-compression)，期待的结果是 filemanager-plugin 最后才执行。

vite.config.js
```
const ViteFilemanager = require("filemanager-plugin").ViteFilemanager;
ViteFilemanager({
        customHooks: [
          {
            hookName: "closeBundle", //  https://cn.vitejs.dev/guide/api-plugin#universal-hooks
            commands: {
              copy: {
                items: [
                  {
                    source: `./dist/${name}.zip`,
                    destination: `./dist/${branch}/xx/`
                  }
                ]
              }
            }
          }
        ]
        // events: {
        //   end: {
        //     copy: {
        //       items: [
        //         {
        //           source: `./dist/${name}.zip`,
        //           destination: `./dist/${branch}/xx/`
        //         }
        //       ]
        //     }
        //   }
        // }
      })
```
基于以上，pnpm build 时 filemanager-plugin 执行的顺序在 vite-plugin-compression 执行前。
发现 vite-plugin-compression 使用了 [enforce: 'post',](https://github.com/vbenjs/vite-plugin-compression/blob/main/packages/core/src/index.ts#L55-L56)
[强制插件排序](https://cn.vitejs.dev/guide/using-plugins#enforcing-plugin-ordering)

filemanager-plugin 是否能提供类似的配置，让使用者根据场景使用？
或者 对于这种情况下，有什么建议吗？

**Comment by xianweics** [comment]
support: https://github.com/xianweics/filemanager-plugin/commit/5e7a1e0e23cbb93215542f7d3f4b91fc8eb7c025

你可以传递任何vite支持的配置去控制这个插件的执行周期。例如
```
const ViteFilemanager = require("filemanager-plugin").ViteFilemanager;
ViteFilemanager({
        customHooks: [
          //  ...
        ],
        enforce: 'post',
        //  ...
      })
```

**Comment by M69W** [comment]
感谢回复。
现已改为别的发布流程，不再依赖 项目node 版本
再次感谢，这个插件确实不错。
