### ISSUE TITLE
How to use in vite?

### ISSUE THREAD

**Issue by 823239259** [xianweics/filemanager-plugin#4]

**Comment by xianweics** [comment]
We have not support vite yet. However, we will support it for next version.

**Comment by xianweics** [comment]
> _No description provided._

Have done. Please try it, according to vite demo in readme.
[1dfa4076a02054f311220bac3f3f9d16945a6b1e](https://github.com/xianweics/filemanager-plugin/commit/1dfa4076a02054f311220bac3f3f9d16945a6b1e)

**Comment by corgoss** [comment]
Hi, I was using Vite with your plugin, but when I used end: {}, it was not working. It only worked if there was a build before. I needed to use a custom hook with the hookName: closeBundle.
